import { invoke } from "@tauri-apps/api/core";
import type { Brief, Plan, TestCase, TestCases } from "./aiRun";
import type { GateVerdict } from "./regressionGate";

/**
 * The test cases, as something that outlives the run.
 *
 * A tester's work product is the case list, not the code that happens to
 * implement it. So the cases are written into the project itself: a JSON file
 * the run reads back - so editing it changes what gets proved - and a Markdown
 * page rendered from it, which is the form a person can actually review.
 *
 * Both live in `.aime/`, which ignores itself in git, so a run cannot slip its
 * paperwork into someone's commit.
 */

export const TEST_CASES_JSON = ".aime/test-cases.json";
export const TEST_CASES_MD = ".aime/test-cases.md";

/** How a case ended up, once the suites have spoken. */
export type CaseOutcome =
  /**
   * Earned, not defaulted: a test citing this case exists on disk, that test
   * was seen failing before the code and every suite that answered is green
   * now, and an artifact made against the running software names the case.
   */
  | "passed"
  /** A test citing this case is named among the failures. */
  | "failed"
  /**
   * Nobody can say: no test cites it, or no reader could name what the runner
   * ran. Never written as a pass — "unproven" and "proven" are the two words
   * this whole pipeline exists to keep apart.
   */
  | "unknown";

/**
 * The one thing still missing before a case could call itself proved.
 *
 * Named so the table can say *why* a case is unproven rather than leaving the
 * reader to reverse-engineer it: each value is the first unmet condition, in
 * the order the pipeline establishes them.
 */
export type CaseGap =
  /** No planned test cites this case at all. */
  | "noTestPlanned"
  /** The planned test's file never appeared in the tree. */
  | "testMissing"
  /**
   * The case's own test was never seen failing before the code existed —
   * either it did not fail, or the runner's output names no tests, in which
   * case nothing can be attributed to any case.
   */
  | "neverRed"
  /** A suite that answered is red, so nothing may be called proved. */
  | "suitesNotGreen"
  /** No artifact made against the running software names this case. */
  | "noEvidence";

/** A case's outcome, and — when it is unproven — the first reason it is. */
export interface CaseVerdict {
  outcome: CaseOutcome;
  gap: CaseGap | null;
}

function pathIn(root: string, file: string): string {
  return `${root.replace(/[\\/]+$/, "")}/${file}`;
}

/**
 * Writes both files. Failure is loud in the console and quiet in the run: a
 * disk that will not take the paperwork is not a reason to abandon the work.
 */
export async function saveTestCases(
  root: string,
  cases: TestCases,
  brief: Brief,
  heading: string,
): Promise<void> {
  try {
    await invoke("write_file", {
      path: pathIn(root, TEST_CASES_JSON),
      content: JSON.stringify({ cases: cases.cases }, null, 2),
    });
    await invoke("write_file", {
      path: pathIn(root, TEST_CASES_MD),
      content: renderTestCases(cases, brief, heading),
    });
  } catch (error: unknown) {
    console.warn("could not write the test cases:", error);
  }
}

/**
 * Reads back what is on disk, so a person's edits are what the run works from.
 *
 * Returns null when there is nothing readable there, which the caller reads as
 * "keep what the phase produced" rather than as an error.
 */
export async function loadTestCases(root: string): Promise<TestCases | null> {
  try {
    const text = await invoke<string>("read_file", { path: pathIn(root, TEST_CASES_JSON) });
    const parsed = JSON.parse(text) as { cases?: unknown };
    const cases = Array.isArray(parsed.cases) ? (parsed.cases as TestCase[]) : [];
    const complete = cases.filter(
      (one) => typeof one.id === "string" && typeof one.then === "string" && one.then !== "",
    );
    return complete.length === 0 ? null : { cases: complete, raw: text };
  } catch {
    return null;
  }
}

/** The Markdown page: the cases grouped under the criterion each one proves. */
export function renderTestCases(cases: TestCases, brief: Brief, heading: string): string {
  const lines = [
    `# Test cases — ${heading}`,
    "",
    `Goal: ${brief.goal}`,
    "",
    `Generated by Aime from \`${TEST_CASES_JSON}\`. Edit that file to change what the run must`,
    "prove; this page is rewritten from it.",
  ];
  for (const criterion of brief.criteria) {
    const mine = cases.cases.filter((one) => one.criterion === criterion.id);
    lines.push("", `## ${criterion.id} — ${criterion.text}`);
    if (mine.length === 0) {
      lines.push("", "_No case covers this criterion._");
      continue;
    }
    for (const one of mine) {
      lines.push(
        "",
        `### ${one.id}`,
        `- **Given** ${one.given || "—"}`,
        `- **When** ${one.when}`,
        `- **Then** ${one.then}`,
        `- **Proved by** ${one.prove || "—"}`,
      );
    }
  }
  // Cases whose criterion no longer exists are still shown: silently dropping
  // someone's case would be the one thing this file must never do.
  const known = new Set(brief.criteria.map((criterion) => criterion.id));
  const orphans = cases.cases.filter((one) => !known.has(one.criterion));
  if (orphans.length > 0) {
    lines.push("", "## Cases with no criterion of that name");
    for (const one of orphans) {
      lines.push("", `### ${one.id} (${one.criterion})`, `- **Then** ${one.then}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

/**
 * What each case ended up proving.
 *
 * Deliberately hard to satisfy — this is the QC's signature line. A case counts
 * as passed only when a planned test cites it, that test's file exists on disk,
 * that very test was seen failing before the code existed, every suite that
 * answered is green now, and an artifact made against the running software
 * names the case. Anything less is "unknown", with the first missing condition
 * attached: a table that reads "passed" because nothing contradicted it would
 * be the most expensive lie in the report.
 */
export function caseOutcomes(
  cases: TestCases,
  plan: Plan | null,
  verdict: GateVerdict | null,
  existingFiles: ReadonlySet<string>,
  provenRed: ReadonlySet<string>,
  evidence: ReadonlyMap<string, string[]>,
): Map<string, CaseVerdict> {
  const failing = (verdict?.suites ?? []).flatMap((suite) => [
    ...suite.after.report.failed,
    ...suite.comparison.broken,
  ]);
  const everythingGreen =
    verdict !== null &&
    verdict.suites.length > 0 &&
    verdict.suites.every((suite) => suite.after.report.passed);

  const outcomes = new Map<string, CaseVerdict>();
  for (const one of cases.cases) {
    const tests = (plan?.tests ?? []).filter((test) => test.case === one.id);
    const written = tests.filter((test) => existingFiles.has(test.file));
    if (tests.some((test) => failing.some((name) => mentions(name, test.name)))) {
      outcomes.set(one.id, { outcome: "failed", gap: null });
      continue;
    }
    const gap =
      tests.length === 0
        ? "noTestPlanned"
        : written.length === 0
          ? "testMissing"
          : !provenRed.has(one.id)
            ? "neverRed"
            : !everythingGreen
              ? "suitesNotGreen"
              : (evidence.get(one.id) ?? []).length === 0
                ? "noEvidence"
                : null;
    outcomes.set(one.id, gap === null ? { outcome: "passed", gap: null } : { outcome: "unknown", gap });
  }
  return outcomes;
}

/**
 * The cases whose own test is among these failure names.
 *
 * How red-then-green becomes a per-case fact rather than a suite-level one: the
 * `tests` phase passes it the names that went red, and only a case found here
 * may ever be reported as proved. A runner whose output names no tests yields
 * an empty set — attributing an anonymous failure to a case would be guessing
 * in the report's favour.
 */
export function casesProvenRed(plan: Plan | null, broken: readonly string[]): Set<string> {
  const proven = new Set<string>();
  for (const test of plan?.tests ?? []) {
    if (broken.some((name) => mentions(name, test.name))) proven.add(test.case);
  }
  return proven;
}

/**
 * Whether a failing test's name is the planned one.
 *
 * Runners print a name the way the code spells it; a plan writes it the way a
 * person says it. So this compares the words, not the punctuation - and it takes
 * a hit only when every word of the planned name is there, which is what keeps
 * "rounds down" from matching every test in the file.
 */
function mentions(reported: string, planned: string): boolean {
  const words = planned.toLowerCase().match(/[a-z0-9]+/g) ?? [];
  if (words.length === 0) return false;
  const haystack = reported.toLowerCase();
  return words.every((word) => haystack.includes(word));
}
