/**
 * Debugging, from the two sides only the real window can show: a breakpoint
 * that survives the app being closed and reopened, and a program that actually
 * stops on it.
 *
 * The second half needs js-debug on the machine, which is a runtime download,
 * so it reports and skips where the adapter is absent rather than failing. What
 * it must never do is skip quietly - a green run that tested half of this
 * would be worse than a red one.
 */
const { strict: assert } = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { fill } = require("../support/fields.cjs");

const projects = [];
/** Programs this spec started itself, to attach to. */
const spawned = [];

function project(name) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `aime-${name}-`));
  projects.push(dir);
  return dir;
}

/**
 * Line 2 is the interesting one: an assignment inside a function, so a frame
 * there has both arguments bound and a local not yet.
 */
const PROGRAM = [
  "function add(a, b) {",
  "  const total = a + b;",
  "  return total;",
  "}",
  "",
  'console.log("total", add(2, 4));',
  "",
].join("\n");

const BREAKPOINT_LINE = 2;

/**
 * A loop, so a condition has something to be true about. The breakpoint goes on
 * line 3 - after the assignment - so the frame it stops in has `doubled` bound,
 * and 100 as the multiplier makes the value unmistakable on screen.
 */
const LOOP_PROGRAM = [
  "for (let i = 0; i < 6; i += 1) {",
  "  const doubled = i * 100;",
  "  console.log(doubled);",
  "}",
  "",
].join("\n");

const LOOP_LINE = 3;

function projectWithAProgram() {
  const dir = project("debug");
  fs.writeFileSync(path.join(dir, "app.js"), PROGRAM);
  return dir;
}

function projectWithALoop() {
  const dir = project("loop");
  fs.writeFileSync(path.join(dir, "app.js"), LOOP_PROGRAM);
  return dir;
}

/** Throws, uncaught, so an exception filter has something to catch. */
function projectThatThrows() {
  const dir = project("throws");
  // Thrown from a timer, not at the top level: under the e2e the program is
  // loaded through wdio's own tsx loader (it leaks in via NODE_OPTIONS), and a
  // top-level throw then surfaces inside the loader's await chain - which
  // js-debug classifies as handled. A timer callback has no promise around it,
  // so this is the uncaught exception the filter is about. Measured.
  fs.writeFileSync(
    path.join(dir, "app.js"),
    ["setTimeout(() => {", '  throw new Error("kaboom");', "}, 0);", ""].join("\n"),
  );
  return dir;
}

/** Prints what it was given, so arguments and environment can be seen arriving. */
function projectThatPrintsItsInput() {
  const dir = project("input");
  fs.writeFileSync(
    path.join(dir, "app.js"),
    ['console.log("arg:", process.argv[2]);', 'console.log("env:", process.env.AIME_E2E);', ""].join("\n"),
  );
  return dir;
}

/**
 * A program that waits for a debugger before its first line (`--inspect-brk`),
 * which is exactly the situation Attach exists for.
 */
function programWaitingForADebugger(port) {
  const dir = project("attach");
  const file = path.join(dir, "app.js");
  fs.writeFileSync(
    file,
    ["let waited = 0;", "setInterval(() => {", "  waited += 1;", "}, 50);", ""].join("\n"),
  );
  const child = require("node:child_process").spawn(
    process.execPath,
    [`--inspect-brk=127.0.0.1:${port}`, file],
    // NODE_OPTIONS carries wdio's own loader; the debuggee must not inherit it.
    { env: { ...process.env, NODE_OPTIONS: "" }, stdio: "ignore", detached: false },
  );
  spawned.push(child);
  return dir;
}

/**
 * A real C# console project, generated by the SDK rather than hand-written: the
 * target framework is whatever this machine's SDK produces, which is not
 * something a fixture should be guessing at.
 */
function dotnetProject() {
  // The long form of the path: measured, Roslyn's project loader asserts on an
  // 8.3 short name, and a Windows temp folder is exactly that.
  const dir = fs.realpathSync.native(project("dotnet"));
  const made = require("node:child_process").spawnSync("dotnet", ["new", "console", "-o", dir, "--force"], {
    encoding: "utf8",
    shell: true,
  });
  if (made.status !== 0) return null;
  const project_file = fs.readdirSync(dir).find((name) => name.endsWith(".csproj"));
  if (project_file === undefined) return null;
  fs.writeFileSync(
    path.join(dir, "Program.cs"),
    [
      "int Add(int a, int b) {",
      "    int total = a + b;",
      "    return total;",
      "}",
      "",
      "System.Console.WriteLine(Add(2, 4));",
      "",
    ].join("\n"),
  );
  return { dir, projectFile: project_file };
}

function projectWithNoProgramInIt() {
  const dir = project("notes");
  fs.writeFileSync(path.join(dir, "NOTES.md"), "# Notes\n\nNothing in this file runs.\n");
  return dir;
}

/**
 * A project whose entry point is not the file a user would be looking at: the
 * manifest names `app.js`, and `helper.js` is a module that does nothing when it
 * is run on its own - which is precisely what F5 used to run.
 */
function projectWithAnEntryPoint() {
  const dir = project("entry");
  fs.writeFileSync(path.join(dir, "package.json"), JSON.stringify({ name: "demo", main: "app.js" }));
  fs.writeFileSync(path.join(dir, "app.js"), PROGRAM);
  fs.writeFileSync(path.join(dir, "helper.js"), "module.exports = { unused: true };\n");
  return dir;
}

/**
 * A Java program that is already running with a JDWP agent — locally what an
 * Android app on an emulator is behind `adb forward tcp:<port> jdwp:<pid>`
 * (measured against a real emulator: the forwarded port behaves exactly like
 * this one). The entry is pre-stamped as verified because the verify gate has
 * its own test above; this fixture exists to prove the attach half.
 */
function javaAttachProject(jdtls, port) {
  const dir = project("java-attach");
  fs.writeFileSync(
    path.join(dir, "Loop.java"),
    [
      "public class Loop {",
      "  public static void main(String[] args) throws InterruptedException {",
      "    int ticks = 0;",
      "    while (true) {",
      "      ticks = ticks + 1;",
      "      Thread.sleep(200);",
      "    }",
      "  }",
      "}",
      "",
    ].join("\n"),
  );
  const compiled = require("node:child_process").spawnSync(
    "javac",
    ["-g", "-d", path.join(dir, "out"), path.join(dir, "Loop.java")],
    { encoding: "utf8", shell: true },
  );
  assert.equal(compiled.status, 0, `javac failed: ${compiled.stderr}`);
  fs.mkdirSync(path.join(dir, ".aime"), { recursive: true });
  fs.writeFileSync(
    path.join(dir, ".aime", "debug-adapters.json"),
    JSON.stringify(
      {
        adapters: [
          {
            id: "java-debug",
            languageIds: ["java"],
            configType: "java",
            transport: "languageServer",
            languageServerCommand: "vscode.java.startDebugSession",
            program: "java",
            args: [
              "-Declipse.application=org.eclipse.jdt.ls.core.id1",
              "-Dosgi.bundles.defaultStartLevel=4",
              "-Declipse.product=org.eclipse.jdt.ls.core.product",
              "-Xmx1G",
              "--add-modules=ALL-SYSTEM",
              "--add-opens",
              "java.base/java.util=ALL-UNNAMED",
              "--add-opens",
              "java.base/java.lang=ALL-UNNAMED",
              "-jar",
              jdtls.launcher,
              "-configuration",
              path.join(jdtls.home, "config_win"),
              "-data",
              path.join(jdtls.home, "..", "jdtls-workspace"),
            ],
            probeArgs: ["-version"],
            // Attach needs no classpath — the program is already running. What
            // it does need (measured against java-debug 0.53.1): `hostName`,
            // because Aime's attach sends a flat `host` the adapter never
            // reads, and `sourcePaths`, or the stopped frame has no source.
            launch: {
              hostName: "127.0.0.1",
              sourcePaths: [dir],
            },
            installHint: "download Eclipse JDT LS and install the java-debug bundle into it",
            verified: {
              program: "Loop.java",
              line: 5,
              at: new Date().toISOString(),
            },
          },
        ],
      },
      null,
      2,
    ),
  );
  const child = require("node:child_process").spawn(
    "java",
    [
      `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:${port}`,
      "-cp",
      path.join(dir, "out"),
      "Loop",
    ],
    { stdio: "ignore", shell: true },
  );
  spawned.push(child);
  return dir;
}

async function bodyText() {
  return (await $("body")).getText();
}

async function waitForText(text, message, timeout = 30_000) {
  const needle = text.toLowerCase();
  await browser.waitUntil(async () => (await bodyText()).toLowerCase().includes(needle), {
    timeout,
    timeoutMsg: message ?? `never saw "${text}"`,
  });
}

/**
 * Opens a folder the only way a driver can: through the recent list.
 *
 * Waiting for the status bar to name this exact folder is not belt and braces.
 * A reload also lets the app adopt the folder it was launched with, and two of
 * these tests open projects holding a file of the same name - so "the tree has
 * an app.js in it" is not evidence that it is *this* project's app.js.
 */
async function open(dir) {
  await browser.execute((recent) => {
    localStorage.setItem("aime.recentFolders", JSON.stringify([{ path: recent, openedAt: Date.now() }]));
  }, dir);
  await browser.refresh();
  await waitForText("RECENT", "the welcome screen never rendered");
  await (await $(`span=${dir.split(/[\\/]/).pop()}`)).click();
  await waitForText(dir, `the status bar never reported ${dir} as the open project`);
}

async function openFromTheTree(name, lines) {
  // The sidebar holds one view at a time, and the Debug view may be the one on
  // screen from an earlier step - the file tree has to be asked for.
  await (await $('button[title="Explorer"]')).click();
  await waitForText(name, "the project never opened");
  await (await $(`span=${name}`)).click();
  // The editor has to be showing the file before a line can be clicked.
  await browser.waitUntil(async () => (await $$(".view-line")).length >= lines, {
    timeout: 20_000,
    timeoutMsg: `the editor never rendered ${name}`,
  });
}

async function openTheProgram() {
  await openFromTheTree("app.js", 6);
}

async function showDebugView() {
  await (await $('button[title="Run and Debug"]')).click();
  await waitForText("breakpoints", "the Run and Debug view never opened");
}

/**
 * Puts the cursor on a line the way a person does - by clicking it.
 *
 * The line is found by its text, not by its position among the rendered
 * elements: Monaco recycles those nodes and their order in the DOM is not the
 * order on screen, which is how an earlier version of this test ended up
 * putting its second breakpoint on a different line than its first.
 */
async function clickLineContaining(fragment) {
  const lines = await $$(".view-line");
  for (const line of lines) {
    if ((await line.getText()).includes(fragment)) {
      await line.click();
      return;
    }
  }
  throw new Error(`no rendered line contains ${fragment}`);
}

async function toggleBreakpointOnAssignment() {
  await clickLineContaining("const total");
  await browser.keys(["F9"]);
}

/**
 * A project that teaches Aime a debugger for a language it does not ship one
 * for — the shape an agent is asked to write (`lib/aiSetup.ts::TEACH_ADAPTER`).
 */
function projectThatTeachesAnAdapter() {
  const dir = project("taught");
  fs.writeFileSync(path.join(dir, "main.lua"), 'local x = 1\nprint(x)\nprint("done")\n');
  fs.mkdirSync(path.join(dir, ".aime"), { recursive: true });
  fs.writeFileSync(
    path.join(dir, ".aime", "debug-adapters.json"),
    JSON.stringify(
      {
        adapters: [
          {
            id: "toy-lua",
            languageIds: ["lua"],
            configType: "lua",
            transport: "stdio",
            program: "node",
            args: [path.join(__dirname, "..", "fixtures", "toy-dap-adapter.cjs")],
            // `node --version` prints and exits, which is what a probe needs.
            probeArgs: ["--version"],
            installHint: "install Node.js",
            verifyWith: { program: "main.lua", line: 2 },
          },
        ],
      },
      null,
      2,
    ),
  );
  return dir;
}

/**
 * A project teaching Aime an adapter that lives inside a language server - the
 * shape java-debug needs, proven without downloading Eclipse.
 */
function projectThatTeachesALanguageServerAdapter() {
  const dir = project("hosted");
  fs.writeFileSync(path.join(dir, "main.rb"), "x = 1\nputs x\nputs 'done'\n");
  fs.mkdirSync(path.join(dir, ".aime"), { recursive: true });
  fs.writeFileSync(
    path.join(dir, ".aime", "debug-adapters.json"),
    JSON.stringify(
      {
        adapters: [
          {
            id: "toy-hosted",
            languageIds: ["ruby"],
            configType: "ruby",
            transport: "languageServer",
            languageServerCommand: "aime.test.startDebugSession",
            program: "node",
            args: [path.join(__dirname, "..", "fixtures", "toy-ls-hosted-adapter.cjs")],
            probeArgs: ["--version"],
            installHint: "install Node.js",
            verifyWith: { program: "main.rb", line: 2 },
          },
        ],
      },
      null,
      2,
    ),
  );
  return dir;
}

/**
 * A project teaching Aime an adapter that runs its program on a device - the one
 * concept mobile adds. The query is a command that prints the JSON shape
 * `flutter devices --machine` prints, so nothing about it is Aime-specific.
 */
function projectThatTeachesADeviceAdapter() {
  const dir = project("device");
  fs.writeFileSync(path.join(dir, "main.dart"), "void main() {\n  print(1);\n}\n");
  fs.mkdirSync(path.join(dir, ".aime"), { recursive: true });
  const devices = JSON.stringify([{ id: "emulator-5554", name: "Pixel 7 API 34" }]);
  fs.writeFileSync(
    path.join(dir, ".aime", "debug-adapters.json"),
    JSON.stringify(
      {
        adapters: [
          {
            id: "toy-device",
            languageIds: ["dart"],
            configType: "dart",
            transport: "stdio",
            program: "node",
            args: [path.join(__dirname, "..", "fixtures", "toy-dap-adapter.cjs")],
            probeArgs: ["--version"],
            installHint: "install the Flutter SDK",
            deviceQuery: {
              command: `node -e "console.log(JSON.stringify(${devices.replaceAll('"', String.fromCharCode(92) + '"')}))"`,
              format: "json",
              idField: "id",
              labelField: "name",
              deviceField: "deviceId",
            },
            verifyWith: { program: "main.dart", line: 2 },
          },
        ],
      },
      null,
      2,
    ),
  );
  return dir;
}

function learnedEntry(dir) {
  return JSON.parse(fs.readFileSync(path.join(dir, ".aime", "debug-adapters.json"), "utf8")).adapters[0];
}

/**
 * The real Eclipse JDT LS with the java-debug bundle installed into it, when an
 * agent has taught this machine one. Installed into Aime's own app data — the
 * same place Aime keeps the adapters it downloads itself — with the bundle
 * registered in `config_win/config.ini`, so an entry needs no Aime code at all.
 */
function jdtlsInstall() {
  const home = path.join(
    process.env.APPDATA ?? os.homedir(),
    "com.iodm.aiminieditor",
    "debug-adapters",
    "jdtls",
  );
  const plugins = path.join(home, "plugins");
  if (!fs.existsSync(plugins)) return null;
  const names = fs.readdirSync(plugins);
  const launcher = names.find(
    (name) => name.startsWith("org.eclipse.equinox.launcher_") && name.endsWith(".jar"),
  );
  const debugBundle = names.some((name) => name.startsWith("com.microsoft.java.debug.plugin"));
  if (!launcher || !debugBundle) return null;
  const javac = require("node:child_process").spawnSync("javac", ["-version"], {
    encoding: "utf8",
    shell: true,
  });
  if (javac.status !== 0) return null;
  return { home, launcher: path.join(plugins, launcher) };
}

/**
 * A Java project taught to Aime the way an agent would write it: the adapter is
 * java-debug living inside JDT LS (the `languageServer` transport), and the
 * launch fields are this project's own. Compiled here because verification
 * launches what already exists — `prepare` belongs to a run, and the test
 * proves that separately by deleting `out` and pressing F5.
 */
function javaProject(jdtls) {
  const dir = project("java");
  fs.writeFileSync(
    path.join(dir, "App.java"),
    [
      "public class App {",
      "  public static void main(String[] args) {",
      "    int doubled = 21 * 2;",
      '    System.out.println("doubled=" + doubled);',
      "  }",
      "}",
      "",
    ].join("\n"),
  );
  // `-g`, or the class has no local-variable table and the debugger can show
  // arguments only — `doubled` would simply be missing from the paused frame.
  const compiled = require("node:child_process").spawnSync(
    "javac",
    ["-g", "-d", path.join(dir, "out"), path.join(dir, "App.java")],
    { encoding: "utf8", shell: true },
  );
  assert.equal(compiled.status, 0, `javac failed: ${compiled.stderr}`);
  fs.mkdirSync(path.join(dir, ".aime"), { recursive: true });
  fs.writeFileSync(
    path.join(dir, ".aime", "debug-adapters.json"),
    JSON.stringify(
      {
        adapters: [
          {
            id: "java-debug",
            languageIds: ["java"],
            configType: "java",
            transport: "languageServer",
            languageServerCommand: "vscode.java.startDebugSession",
            program: "java",
            args: [
              "-Declipse.application=org.eclipse.jdt.ls.core.id1",
              "-Dosgi.bundles.defaultStartLevel=4",
              "-Declipse.product=org.eclipse.jdt.ls.core.product",
              "-Xmx1G",
              "--add-modules=ALL-SYSTEM",
              "--add-opens",
              "java.base/java.util=ALL-UNNAMED",
              "--add-opens",
              "java.base/java.lang=ALL-UNNAMED",
              "-jar",
              jdtls.launcher,
              "-configuration",
              path.join(jdtls.home, "config_win"),
              "-data",
              path.join(jdtls.home, "..", "jdtls-workspace"),
            ],
            probeArgs: ["-version"],
            prepare: { command: "javac -g -d out App.java" },
            // Measured against java-debug 0.53.1: `mainClass` and `classPaths`
            // are what launches, and without `sourcePaths` the stopped frame
            // comes back with no source path for the editor to open.
            launch: {
              mainClass: "App",
              classPaths: [path.join(dir, "out")],
              sourcePaths: [dir],
            },
            installHint: "download Eclipse JDT LS and install the java-debug bundle into it",
            verifyWith: { program: "App.java", line: 3 },
          },
        ],
      },
      null,
      2,
    ),
  );
  return dir;
}

describe("Debugging", () => {
  after(() => {
    for (const child of spawned) {
      try {
        child.kill();
      } catch {
        /* it may have exited with the session that was attached to it */
      }
    }
    for (const dir of projects) {
      try {
        fs.rmSync(dir, { recursive: true, force: true });
      } catch {
        /* Windows keeps a handle on the folder the app has open */
      }
    }
  });

  it("sets a breakpoint from the editor and keeps it after a restart", async () => {
    const dir = projectWithAProgram();
    await open(dir);
    await openTheProgram();
    await showDebugView();
    await waitForText("no breakpoints yet", "the panel should start with none");

    await toggleBreakpointOnAssignment();
    await waitForText(
      `app.js:${BREAKPOINT_LINE}`,
      "F9 on line 2 did not put a breakpoint in the panel's list",
    );

    // Reopening the project is the real test: breakpoints belong to a project,
    // not to a session, and nobody wants to set them again every morning.
    await open(dir);
    await showDebugView();
    await waitForText(
      `app.js:${BREAKPOINT_LINE}`,
      "the breakpoint did not survive closing and reopening the project",
    );

    // And removing it is not a reload away either. Opening the file puts the
    // Explorer back on screen, so the panel has to be asked for again before
    // its emptiness means anything.
    await openTheProgram();
    await toggleBreakpointOnAssignment();
    await showDebugView();
    await waitForText("no breakpoints yet", "toggling the same line again did not remove the breakpoint");
  });

  it("stops the program on the breakpoint and shows the frame it stopped in", async () => {
    await open(projectWithAProgram());
    await openTheProgram();
    await showDebugView();

    // The panel says which of the two it is: a button to start, or an offer to
    // fetch the adapter first.
    const offersDownload = (await bodyText()).toLowerCase().includes("download it");
    if (offersDownload) {
      console.log(
        "[debug.e2e] SKIPPED the run: js-debug is not downloaded on this machine, so there is " +
          "nothing to stop the program with. The breakpoint test above still ran.",
      );
      return;
    }

    await toggleBreakpointOnAssignment();
    await waitForText(`app.js:${BREAKPOINT_LINE}`, "the breakpoint was not registered before starting");

    await browser.keys(["F5"]);
    // Starting the adapter pays for Node's own boot, and js-debug then opens a
    // second session before any of this appears.
    await waitForText("call stack", "the run never reached a paused state", 60_000);
    await waitForText("add", "the call stack does not name the function it stopped in", 30_000);
    // The arguments of the frame it stopped in, fetched from the adapter.
    await waitForText("total", "the Variables section never listed the frame's own names", 30_000);

    const paused = await bodyText();
    assert.ok(
      /\ba\b/.test(paused) && paused.includes("2"),
      "the paused frame should show the argument a = 2",
    );

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the session",
    });
  });

  /**
   * What "debug the project" means, from the only angle that proves it: the
   * breakpoint is in the entry point, the file on screen is a different one, and
   * the program still stops. Before target detection, F5 ran the file in front
   * of the user - here that would have run a module with no entry point and
   * ended in silence.
   */
  it("runs the project's entry point, not the file that happens to be open", async () => {
    await open(projectWithAnEntryPoint());

    await openFromTheTree("app.js", 6);
    await toggleBreakpointOnAssignment();
    await showDebugView();
    await waitForText(`app.js:${BREAKPOINT_LINE}`, "the breakpoint was not registered in the entry point");

    // The file in front of the user is now the helper, and the panel must still
    // say - and run - the project's program.
    await openFromTheTree("helper.js", 1);
    await showDebugView();
    await waitForText("debug app.js", "the panel does not name the project's entry point as the target");

    if ((await bodyText()).toLowerCase().includes("download it")) {
      console.log(
        "[debug.e2e] SKIPPED the run: js-debug is not downloaded on this machine. The target was " +
          "still resolved to app.js above, which is the part this test is about.",
      );
      return;
    }

    await browser.keys(["F5"]);
    await waitForText("call stack", "F5 with the helper open never reached a paused state", 60_000);
    await waitForText("add", "the run stopped somewhere other than the entry point", 30_000);

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the session",
    });
  });

  /**
   * The whole point of a learnable catalog: a language Aime ships no adapter for
   * becomes debuggable because an entry was written for it — and does **not**
   * count as debuggable until Aime has watched a session stop on a real
   * breakpoint. Both halves are asserted here, in that order, because the second
   * one is the only thing standing between an AI editor and a confident lie.
   */
  it("debugs a language it was taught, but only after it has watched it stop", async () => {
    const dir = projectThatTeachesAnAdapter();
    assert.equal(learnedEntry(dir).verified, undefined, "the entry starts unverified");

    await open(dir);
    await openFromTheTree("main.lua", 3);
    await showDebugView();

    // Read, probed (the program is on PATH) - and refused all the same.
    await waitForText("toy-lua", "the taught adapter was not picked up at all");
    await waitForText("has not seen it stop", "an unproven adapter must not be offered as working");

    await (await $("button*=Check it on a real breakpoint")).click();
    // After a real stop: the panel offers the run, which is only reachable once
    // the entry counts as verified.
    await waitForText("debug main.lua", "verification did not make the language debuggable", 60_000);

    const stamped = learnedEntry(dir).verified;
    assert.ok(stamped, "Aime did not record what it saw");
    assert.equal(stamped.line, 2, `the stamp should hold the line it stopped on: ${JSON.stringify(stamped)}`);
  });

  /**
   * A condition is the difference between a debugger and a slot machine: without
   * one, stopping on the fourth pass of a loop means pressing F5 three times.
   * The adapter evaluates it - Aime only sends it - so this asserts the thing
   * that can actually break: that it arrives, and that the program stops on the
   * pass the condition names.
   */
  it("stops on the pass of a loop the condition names, not the first one", async () => {
    await open(projectWithALoop());
    await openFromTheTree("app.js", 4);
    await showDebugView();
    if ((await bodyText()).toLowerCase().includes("download it")) {
      console.log("[debug.e2e] SKIPPED: js-debug is not downloaded on this machine.");
      return;
    }

    await openFromTheTree("app.js", 4);
    await clickLineContaining("console.log(doubled)");
    // Shift+F9: a breakpoint with a condition, in one gesture.
    await browser.keys(["Shift", "F9"]);
    await waitForText("stop only when", "Shift+F9 did not open the breakpoint condition");
    await fill(await $('input[placeholder="i === 3"]'), "i === 4");
    await (await $("button*=Save")).click();

    await showDebugView();
    await waitForText(`app.js:${LOOP_LINE}`, "the conditional breakpoint is not in the list");

    await browser.keys(["F5"]);
    // The wait *is* the assertion, and it has to be on something only a paused
    // frame can show: "doubled" is also the text of the line on screen, and
    // "call stack" appears the moment a run starts. 400 is the value of
    // `doubled` on the fifth pass - on the first it would be 0, which is
    // exactly what an ignored condition looks like.
    await waitForText("400", "the program did not stop on the pass where i = 4", 60_000);

    // A watch is evaluated in the frame the program stopped in, so this is the
    // only place it can be proven: doubled is 400 here, and nothing else on
    // screen says 401.
    await fill(await $(`input[placeholder="Add an expression…"]`), "doubled + 1");
    await browser.keys(["Enter"]);
    await waitForText("401", "the watch was not evaluated in the frame the program stopped in");

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the session",
    });
  });

  /**
   * A debugger that cannot pass arguments can only run the programs that need
   * none. The program prints both back, so the Debug Console is the proof - and
   * the values go through `.aime/launch.json`, which the assertion reads too.
   */
  it("passes the arguments and environment a target was given", async () => {
    const dir = projectThatPrintsItsInput();
    await open(dir);
    await openFromTheTree("app.js", 2);
    await showDebugView();
    if ((await bodyText()).toLowerCase().includes("download it")) {
      console.log("[debug.e2e] SKIPPED: js-debug is not downloaded on this machine.");
      return;
    }

    await (await $("button*=Arguments")).click();
    await fill(await $('input[placeholder="runserver --port 8080"]'), '"hello there"');
    await fill(await $('textarea[placeholder^="NODE_ENV=test"]'), "AIME_E2E=works");
    await (await $("button*=Save")).click();

    await browser.keys(["F5"]);
    await waitForText("arg: hello there", "the argument never reached the program", 60_000);
    await waitForText("env: works", "the environment variable never reached the program", 30_000);

    const stored = JSON.parse(fs.readFileSync(path.join(dir, ".aime", "launch.json"), "utf8"));
    const only = Object.values(stored.targets)[0];
    assert.deepEqual(only.args, ["hello there"], `arguments were not stored: ${JSON.stringify(stored)}`);
    assert.deepEqual(
      only.env,
      { AIME_E2E: "works" },
      `environment was not stored: ${JSON.stringify(stored)}`,
    );
  });

  /**
   * Mobile's one extra concept: the program runs on a device, and the adapter
   * takes its id as a launch field. The list comes from the adapter's own
   * command - here one that prints exactly what `flutter devices --machine`
   * prints - and the proof is the id arriving in the launch request, which the
   * fixture echoes back into the console.
   */
  it("runs on the device its adapter listed, and says so in the launch", async () => {
    const dir = projectThatTeachesADeviceAdapter();
    await open(dir);
    await openFromTheTree("main.dart", 3);
    await showDebugView();
    // A taught adapter is a dead end until it has been checked, so the device
    // row belongs after that - the same order a user would meet it in.
    await (await $("button*=Check it on a real breakpoint")).click();
    await waitForText("debug main.dart", "the device adapter was never verified", 60_000);
    await (await $("button*=Pick a device")).click();
    await waitForText("pixel 7 api 34", "the adapter's own device query never reached the picker", 30_000);
    await (await $("div*=Pixel 7 API 34")).click();

    await browser.keys(["F5"]);
    // The fixture prints the launch request it received, so this is the device id
    // arriving in the field the adapter said it wanted.
    await waitForText(
      '"deviceId":"emulator-5554"',
      "the chosen device did not reach the launch request",
      60_000,
    );
    await browser.keys(["Shift", "F5"]);
  });

  /**
   * The third transport shape: an adapter that has no process of its own, only a
   * language server that will open a debug session on request. Aime does the LSP
   * handshake, sends the command, reads the port out of the answer and connects.
   * java-debug is exactly this, and this test is what proves Aime's half of it
   * without several hundred megabytes of Eclipse.
   */
  it("debugs through an adapter that lives inside a language server", async () => {
    const dir = projectThatTeachesALanguageServerAdapter();
    await open(dir);
    await openFromTheTree("main.rb", 3);
    await showDebugView();
    await waitForText("toy-hosted", "the taught language-server adapter was not picked up");
    await waitForText("has not seen it stop", "an unproven adapter must not be offered as working");

    await (await $("button*=Check it on a real breakpoint")).click();
    await waitForText("debug main.rb", "the language server never handed over a working session", 60_000);
    assert.ok(learnedEntry(dir).verified, "Aime did not record what it saw");
  });

  /**
   * The same transport against the real thing: Eclipse JDT LS 1.39.0 with
   * java-debug 0.53.1 installed as a bundle. The toy above proves Aime's half
   * cheaply on every machine; this proves the whole road on one that has the
   * toolchain — verification first, then a run that must rebuild what the test
   * deleted, because `prepare` runs on F5 and a stop without the class files
   * would be impossible.
   */
  it("debugs Java through the real JDT LS it was taught", async () => {
    const jdtls = jdtlsInstall();
    if (jdtls === null) {
      console.log("[debug.e2e] SKIPPED: no JDT LS with java-debug in Aime's app data.");
      return;
    }
    const dir = javaProject(jdtls);
    await open(dir);
    await openFromTheTree("App.java", 3);
    await showDebugView();
    await waitForText("java-debug", "the taught java adapter was not picked up");
    await waitForText("has not seen it stop", "an unproven adapter must not be offered as working");

    await (await $("button*=Check it on a real breakpoint")).click();
    await waitForText("debug app.java", "JDT LS never handed over a working session", 120_000);
    const entry = learnedEntry(dir);
    assert.ok(entry.verified, "Aime did not record what it saw");
    assert.equal(entry.verified.line, 3, "Aime stamped a different line than the one it was told");

    // The run half: `out` is gone, so only Aime running the entry's `prepare`
    // (javac) can put the class back for the debugger to stop in.
    fs.rmSync(path.join(dir, "out"), { recursive: true, force: true });
    await openFromTheTree("App.java", 3);
    // The println line, not the assignment: a breakpoint stops *before* its
    // line runs, and a frame paused on line 3 has no `doubled` yet.
    await clickLineContaining("System.out.println");
    await browser.keys(["F9"]);
    // The Variables panel lives in the Run and Debug view, so it has to be the
    // one on screen for the stopped frame to prove itself below.
    await showDebugView();
    await browser.keys(["F5"]);
    // 42 is `doubled` in the paused frame; the source shows only `21 * 2`, so
    // nothing but a real stop can put it on screen.
    await waitForText("42", "the run never rebuilt and stopped in App.java", 120_000);

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the Java session",
    });
  });

  /**
   * Attaching to a JVM that is already running — which is what Android
   * debugging is: `adb forward tcp:<port> jdwp:<pid>` makes an app on an
   * emulator reachable exactly like this local program (measured against a
   * real emulator-hosted app; the stop landed in its Activity source). The
   * program ticks every 200 ms, so the breakpoint proves execution was caught
   * mid-flight rather than held at entry.
   */
  it("attaches to a running Java program over JDWP, the way Android is debugged", async () => {
    const jdtls = jdtlsInstall();
    if (jdtls === null) {
      console.log("[debug.e2e] SKIPPED: no JDT LS with java-debug in Aime's app data.");
      return;
    }
    const port = 9332;
    const dir = javaAttachProject(jdtls, port);
    await open(dir);
    await openFromTheTree("Loop.java", 5);
    await clickLineContaining("ticks = ticks + 1");
    await browser.keys(["F9"]);
    await showDebugView();

    await (await $("button*=Attach to a running program")).click();
    await fill(await $('input[placeholder="9229"]'), String(port));
    await (await $("button*=Attach")).click();

    await waitForText("paused:", "attaching never stopped the running JVM", 120_000);
    // The frame has to be the fixture's own source, not a JDI placeholder.
    await waitForText("loop.main", "the stopped frame did not resolve to Loop.java", 30_000);

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the attach session",
    });
  });

  /**
   * C# is the one language where a run builds first: netcoredbg attaches to an
   * assembly, not to a .cs file. So this test is about two things at once - the
   * build Aime runs before the debugger sees anything, and the stop itself.
   */
  it("builds a C# project and stops in the source it came from", async () => {
    const made = dotnetProject();
    if (made === null) {
      console.log("[debug.e2e] SKIPPED: no .NET SDK on this machine.");
      return;
    }
    await open(made.dir);
    await openFromTheTree("Program.cs", 6);
    await showDebugView();
    if ((await bodyText()).toLowerCase().includes("download it")) {
      console.log("[debug.e2e] SKIPPED: netcoredbg is not downloaded on this machine.");
      return;
    }
    // The target is the project, not the file - that is what the panel must say.
    await waitForText(`debug ${made.projectFile}`, "the panel did not resolve the C# project as the target");

    await openFromTheTree("Program.cs", 6);
    await clickLineContaining("int total = a + b");
    await browser.keys(["F9"]);
    await showDebugView();
    await waitForText("program.cs:2", "F9 did not put a breakpoint in the C# file");

    await browser.keys(["F5"]);
    // The build is announced, then the debugger stops in the source.
    await waitForText("building", "the run did not announce the build", 30_000);
    await waitForText("total", "the C# program never stopped in its own source", 180_000);

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the session",
    });
  });

  /**
   * The Roslyn language server, which Aime downloads itself and has to be told
   * which project it is looking at. The status chip turns green only once the
   * server started, answered `initialize` and survived - and it does not survive
   * a client that answers `workspace/configuration` with the wrong shape, which
   * is the bug this test would have caught.
   */
  it("runs the C# language server it downloaded, on the project it was told about", async () => {
    const made = dotnetProject();
    if (made === null) {
      console.log("[debug.e2e] SKIPPED: no .NET SDK on this machine.");
      return;
    }
    await open(made.dir);
    await openFromTheTree("Program.cs", 6);
    const chip = await $("button*=csharp");
    if (!(await chip.isExisting())) {
      console.log("[debug.e2e] SKIPPED: the C# language server is not downloaded on this machine.");
      return;
    }
    await browser.waitUntil(async () => (await chip.getAttribute("title")).toLowerCase().includes("active"), {
      timeout: 120_000,
      timeoutMsg: `the C# server never came up: ${await chip.getAttribute("title")}`,
    });
  });

  /**
   * Attaching to something already running, which is how a server is debugged.
   * `--inspect-brk` holds the program before its first line, so a successful
   * attach is a paused program - and nothing else on screen can fake that.
   */
  it("attaches to a program that is already waiting on a port", async () => {
    const port = 9331;
    await open(programWaitingForADebugger(port));
    await openFromTheTree("app.js", 4);
    await showDebugView();
    if ((await bodyText()).toLowerCase().includes("download it")) {
      console.log("[debug.e2e] SKIPPED: js-debug is not downloaded on this machine.");
      return;
    }

    await (await $("button*=Attach to a running program")).click();
    await fill(await $('input[placeholder="9229"]'), String(port));
    await (await $("button*=Attach")).click();

    // Node holds the first line for the debugger, so an attach that worked is a
    // program that is paused - the reason is the adapter's own word for it.
    await waitForText("paused:", "attaching did not reach the waiting program", 60_000);

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the session",
    });
  });

  /**
   * Stopping where a program throws, which is the difference between reading a
   * stack trace and standing in the frame that produced it. Measured: js-debug
   * offers "Caught"/"Uncaught" and defaults **both off**, so the first run dies
   * without stopping - and that first run is what puts the adapter's own filters
   * in front of the user. Both halves are asserted.
   */
  it("stops where an exception is thrown, once that is switched on", async () => {
    const dir = projectThatThrows();
    await browser.execute((root) => {
      const key = `aime.debugExceptions.${root.replaceAll("\\", "/").toLowerCase()}`;
      localStorage.setItem(key, JSON.stringify({ javascript: ["uncaught"] }));
    }, dir);
    await open(dir);
    await openFromTheTree("app.js", 3);
    await showDebugView();
    if ((await bodyText()).toLowerCase().includes("download it")) {
      console.log("[debug.e2e] SKIPPED: js-debug is not downloaded on this machine.");
      return;
    }

    await browser.keys(["F5"]);
    await waitForText("call stack", "F5 did not start a run at all", 30_000);
    // "Paused: exception" is the adapter's own reason, and only a real stop
    // renders it - the word "kaboom" is also in the editor.
    try {
      await waitForText("paused: exception", "the program did not stop where it threw", 60_000);
    } catch (err) {
      throw new Error(`${err.message}
--- on screen ---
${(await bodyText()).slice(0, 1200)}`);
    }

    // The checkbox is the stored choice, both ways round: it shows what the run
    // used, and unticking it writes the change back.
    const box = await (await $("label*=Uncaught Exceptions")).$("input");
    assert.ok(await box.isSelected(), "the filter the run used is not ticked in the panel");
    await box.click();
    assert.ok(!(await box.isSelected()), "unticking the filter did not take");

    await browser.keys(["Shift", "F5"]);
    await browser.waitUntil(async () => !(await bodyText()).toLowerCase().includes("call stack"), {
      timeout: 30_000,
      timeoutMsg: "Shift+F5 did not end the session",
    });
  });

  /**
   * The regression a user reported: `dap_availability` answers "no adapter" for
   * Markdown exactly as it does for C++, and the editor read both as a gap
   * worth offering to fill - so a README was met with an offer to set up a
   * debugger, and F9 put a breakpoint in it. Whether a file can be debugged is
   * whether Aime drives an adapter for its language, and nothing else.
   */
  it("offers no debugger and takes no breakpoint in a file that is not a program", async () => {
    await open(projectWithNoProgramInIt());
    await openFromTheTree("NOTES.md", 3);

    const body = (await bodyText()).toLowerCase();
    assert.ok(!body.includes("let ai set it up"), "a Markdown file was offered a debugger it can never use");

    // The gesture itself is withdrawn, not offered and then refused.
    await (await $(".monaco-editor .view-line")).click({ button: "right" });
    await waitForText("suggest code here", "the editor's own menu never opened");
    assert.ok(
      !(await bodyText()).toLowerCase().includes("toggle breakpoint"),
      "the context menu offered a breakpoint in a file that can never hold one",
    );
    await browser.keys(["Escape"]);

    await clickLineContaining("Notes");
    await browser.keys(["F9"]);
    await showDebugView();
    await waitForText("does not debug", "the panel should say plainly that Aime does not debug these");
    await waitForText("no breakpoints yet", "F9 left a breakpoint in a Markdown file");
    // The teach offer exists for program languages (test below) and must not
    // leak back onto documents - that would be session 6's bug returning.
    assert.ok(
      !(await bodyText()).toLowerCase().includes("let ai set it up"),
      "the Run and Debug view offered to teach a debugger for a Markdown file",
    );
  });

  /**
   * The php case that exposed the gap: completions work (the server installs
   * itself), no adapter exists - and the panel used to offer nothing at all,
   * even though a taught adapter (learned.rs + dap_verify) could close the
   * gap. The offer lives here, where debugging intent is expressed; documents
   * stay quiet, which the test above pins down.
   */
  it("offers to teach a debugger for a program language it has no adapter for", async () => {
    const dir = project("php");
    fs.writeFileSync(path.join(dir, "index.php"), "<?php\n$total = 2 + 4;\necho $total;\n");
    await open(dir);
    await openFromTheTree("index.php", 3);
    await showDebugView();
    await waitForText("does not debug php", "the panel should still say plainly that php has no adapter");
    const offer = await $("button*=Let AI set it up");
    assert.ok(await offer.isExisting(), "a teachable language got no offer to teach Aime its debugger");
    // Not clicked: pressing it starts a real AI run, and this suite spends no
    // money. The run path itself is `useSetup.start`, covered by its own tests.
  });
});
